//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Accountancy.InputData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputDataValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputDataValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Accountancy.InputData.InputDataValidationMessage", typeof(InputDataValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định danh mã chứng từ không đúng, vui lòng chọn lại.
        /// </summary>
        public static string BillCodeError {
            get {
                return ResourceManager.GetString("BillCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ không được phép trước ngày chốt sổ.
        /// </summary>
        public static string BillDateMustBeGreaterThanClosingDate {
            get {
                return ResourceManager.GetString("BillDateMustBeGreaterThanClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chứng từ.
        /// </summary>
        public static string BillNotFound {
            get {
                return ResourceManager.GetString("BillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chuyển giá trị {0}, dòng {1}, trường {2} sang kiểu ngày tháng.
        /// </summary>
        public static string CannotConvertValueInRowFieldToDateTime {
            get {
                return ResourceManager.GetString("CannotConvertValueInRowFieldToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu {0} không tìm thấy.
        /// </summary>
        public static string FieldNameNotFound {
            get {
                return ResourceManager.GetString("FieldNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy trường dữ liệu.
        /// </summary>
        public static string FieldNotFound {
            get {
                return ResourceManager.GetString("FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy trường dữ liệu tham chiếu.
        /// </summary>
        public static string FieldRefNotFound {
            get {
                return ResourceManager.GetString("FieldRefNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu {0} yêu cầu bắt buộc.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thiết lập sinh mã cho trường {0}.
        /// </summary>
        public static string GenerateCodeConfigForFieldNotFound {
            get {
                return ResourceManager.GetString("GenerateCodeConfigForFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình sinh mã {0}: {1}.
        /// </summary>
        public static string GenerateCodeFieldBadRequest {
            get {
                return ResourceManager.GetString("GenerateCodeFieldBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sinh mã {0}.
        /// </summary>
        public static string GenerateCodeFieldError {
            get {
                return ResourceManager.GetString("GenerateCodeFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy loại chứng từ.
        /// </summary>
        public static string InputTypeNotFound {
            get {
                return ResourceManager.GetString("InputTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại chứng từ cần thay đổi.
        /// </summary>
        public static string ListBillsToUpdateIsEmpty {
            get {
                return ResourceManager.GetString("ListBillsToUpdateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị mới truyền vào không hợp lệ.
        /// </summary>
        public static string NewValueIsInvalid {
            get {
                return ResourceManager.GetString("NewValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị cũ truyền vào không hợp lệ.
        /// </summary>
        public static string OldValueIsInvalid {
            get {
                return ResourceManager.GetString("OldValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ tài khoản đối ứng tương ứng {0}.
        /// </summary>
        public static string PairAccountError {
            get {
                return ResourceManager.GetString("PairAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chứng từ không hợp lệ. Mã lỗi: {0}.
        /// </summary>
        public static string ProcessActionResultErrorCode {
            get {
                return ResourceManager.GetString("ProcessActionResultErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu liên quan (tham chiếu) tới &quot;{0}&quot; ({1}) không tồn tại.
        /// </summary>
        public static string RefFieldNotExisted {
            get {
                return ResourceManager.GetString("RefFieldNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục liên kết {0} không tìm thấy!.
        /// </summary>
        public static string RefTableNotFound {
            get {
                return ResourceManager.GetString("RefTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần thông tin trường {0} trước thông tin {1}.
        /// </summary>
        public static string RequireFieldBeforeField {
            get {
                return ResourceManager.GetString("RequireFieldBeforeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        public static string SingleRowArea {
            get {
                return ResourceManager.GetString("SingleRowArea", resourceCulture);
            }
        }
    }
}
