//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.PurchaseOrder.Po {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchaseOrderActivityLogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseOrderActivityLogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.PurchaseOrder.Po.PurchaseOrderActivityLogMessage", typeof(PurchaseOrderActivityLogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt PO &quot;{0}&quot;.
        /// </summary>
        public static string CensorApprove {
            get {
                return ResourceManager.GetString("CensorApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối duyệt PO &quot;{0}&quot;.
        /// </summary>
        public static string CensorReject {
            get {
                return ResourceManager.GetString("CensorReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kiểm tra PO &quot;{0}&quot;.
        /// </summary>
        public static string CheckApprove {
            get {
                return ResourceManager.GetString("CheckApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra từ chối PO &quot;{0}&quot;.
        /// </summary>
        public static string CheckReject {
            get {
                return ResourceManager.GetString("CheckReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo PO &quot;{0}&quot;.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tiến độ PO &quot;{0}&quot;: {1}.
        /// </summary>
        public static string CreatePoTrack {
            get {
                return ResourceManager.GetString("CreatePoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa PO &quot;{0}&quot;.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tiến độ PO &quot;{0}&quot;: {1}.
        /// </summary>
        public static string DeletePoTrack {
            get {
                return ResourceManager.GetString("DeletePoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập PO &quot;{0}&quot; từ excel.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi duyệt PO &quot;{0}&quot;.
        /// </summary>
        public static string SendToCensor {
            get {
                return ResourceManager.GetString("SendToCensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật PO &quot;{0}&quot;.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái {0} PO &quot;{1}&quot;.
        /// </summary>
        public static string UpdatePoProcessStatus {
            get {
                return ResourceManager.GetString("UpdatePoProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tiến độ PO &quot;{0}&quot;: {1}.
        /// </summary>
        public static string UpdatePoTrack {
            get {
                return ResourceManager.GetString("UpdatePoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tiến độ PO &quot;{0}&quot;: {1}.
        /// </summary>
        public static string UpdatePoTrackMulti {
            get {
                return ResourceManager.GetString("UpdatePoTrackMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vật tư dư thừa {0}, PO &quot;{1}&quot;.
        /// </summary>
        public static string UpdatePurchaseOrderExcess {
            get {
                return ResourceManager.GetString("UpdatePurchaseOrderExcess", resourceCulture);
            }
        }
    }
}
