//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.PurchaseOrder.Po {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchaseOrderOutsourceValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseOrderOutsourceValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.PurchaseOrder.Po.PurchaseOrderOutsourceValidationMessage", typeof(PurchaseOrderOutsourceValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ giao hàng quá dài.
        /// </summary>
        public static string DeleveryDestinationTooLong {
            get {
                return ResourceManager.GetString("DeleveryDestinationTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO đã được duyệt.
        /// </summary>
        public static string PoAlreadyApproved {
            get {
                return ResourceManager.GetString("PoAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO đã được kiểm tra.
        /// </summary>
        public static string PoAlreadyChecked {
            get {
                return ResourceManager.GetString("PoAlreadyChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO đã từ chối.
        /// </summary>
        public static string PoAlreadyRejected {
            get {
                return ResourceManager.GetString("PoAlreadyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO đã từ chối kiểm tra.
        /// </summary>
        public static string PoHasBeenFailAtCheck {
            get {
                return ResourceManager.GetString("PoHasBeenFailAtCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO chưa được qua kiểm tra.
        /// </summary>
        public static string PoNotPassCheckYet {
            get {
                return ResourceManager.GetString("PoNotPassCheckYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO chưa được gửi để duyệt.
        /// </summary>
        public static string PoNotSentToCensorYet {
            get {
                return ResourceManager.GetString("PoNotSentToCensorYet", resourceCulture);
            }
        }
    }
}
