//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VErp.Services.Stock.Service.Resources.Product {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductActivityLogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductActivityLogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VErp.Services.Stock.Service.Resources.Product.ProductActivityLogMessage", typeof(ProductActivityLogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép BOM mặt hàng từ {0} sang {1}.
        /// </summary>
        internal static string CopyBom {
            get {
                return ResourceManager.GetString("CopyBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép vật tư tiêu hao mặt hàng từ {0} sang {1}.
        /// </summary>
        internal static string CopyConsumption {
            get {
                return ResourceManager.GetString("CopyConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới mặt hàng {0}.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới chi tiết mặt hàng {0}.
        /// </summary>
        internal static string CreateProductPart {
            get {
                return ResourceManager.GetString("CreateProductPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa mặt hàng {0}.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Bom cho mặt hàng {0}.
        /// </summary>
        internal static string ImportBom {
            get {
                return ResourceManager.GetString("ImportBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import vật tư tiêu hao cho mặt hàng {0}.
        /// </summary>
        internal static string ImportConsumption {
            get {
                return ResourceManager.GetString("ImportConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật mặt hàng {0}.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tệp đính kèm cho mặt hàng {0}.
        /// </summary>
        internal static string UpdateAttachment {
            get {
                return ResourceManager.GetString("UpdateAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật BOM mặt hàng {0}.
        /// </summary>
        internal static string UpdateBom {
            get {
                return ResourceManager.GetString("UpdateBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vật tư tiêu hao {0} cho mặt hàng {1}.
        /// </summary>
        internal static string UpdateDetailMaterialConsumption {
            get {
                return ResourceManager.GetString("UpdateDetailMaterialConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật TT chung mặt hàng {0}.
        /// </summary>
        internal static string UpdateGeneralInfo {
            get {
                return ResourceManager.GetString("UpdateGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vật tư tiêu hao mặt hàng {0}.
        /// </summary>
        internal static string UpdateMaterialConsumption {
            get {
                return ResourceManager.GetString("UpdateMaterialConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật TT bán mặt hàng {0}.
        /// </summary>
        internal static string UpdateSellInfo {
            get {
                return ResourceManager.GetString("UpdateSellInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật TT lưu kho mặt hàng {0}.
        /// </summary>
        internal static string UpdateStockInfo {
            get {
                return ResourceManager.GetString("UpdateStockInfo", resourceCulture);
            }
        }
    }
}
