//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VErp.Services.Stock.Service.Resources.Product {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VErp.Services.Stock.Service.Resources.Product.ProductMessage", typeof(ProductMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa mặt hàng do mặt hàng đang được sử dụng.
        /// </summary>
        internal static string CanNotDeleteProductWhichInUsed {
            get {
                return ResourceManager.GetString("CanNotDeleteProductWhichInUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy khách hàng có mã {0}.
        /// </summary>
        internal static string CustomerWithCodeNotFound {
            get {
                return ResourceManager.GetString("CustomerWithCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy khách hàng có tên {0}.
        /// </summary>
        internal static string CustomerWithNameNotFound {
            get {
                return ResourceManager.GetString("CustomerWithNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục mặt hàng mặc định không tồn tại.
        /// </summary>
        internal static string DefaultProductCateNotFound {
            get {
                return ResourceManager.GetString("DefaultProductCateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bộ phận {0} sử dụng mặt hàng {1}.
        /// </summary>
        internal static string DepartmentOfMaterialNotFound {
            get {
                return ResourceManager.GetString("DepartmentOfMaterialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại nhiều hơn 1 thiết lập cho 1 khách hàng.
        /// </summary>
        internal static string ExistMoreSameCustomerProduct {
            get {
                return ResourceManager.GetString("ExistMoreSameCustomerProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hiện các chi tiết sử dụng không tồn tại trong BOM mặt hàng. Các chi tiết sử dụng: {0}.
        /// </summary>
        internal static string ImportConsumBomNotExistedInProduct {
            get {
                return ResourceManager.GetString("ImportConsumBomNotExistedInProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hiện chi tiết sử dụng có mã trùng nhau cùng sử dụng vật liệu tiêu hao trong cùng 1 nhóm. Các vật liệu tiêu hao: {0}.
        /// </summary>
        internal static string ImportConsumDuplicateSamePartInSameGroup {
            get {
                return ResourceManager.GetString("ImportConsumDuplicateSamePartInSameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhóm vật tư tiêu hao {0}.
        /// </summary>
        internal static string ImportConsumptionGroupNotFound {
            get {
                return ResourceManager.GetString("ImportConsumptionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại nhiều hơn 1 mặt hàng {0}.
        /// </summary>
        internal static string ImportMultipleProductsFound {
            get {
                return ResourceManager.GetString("ImportMultipleProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần chọn danh mục cho mặt hàng {0}.
        /// </summary>
        internal static string ImportNeedProductCateForProduct {
            get {
                return ResourceManager.GetString("ImportNeedProductCateForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mặc định cho mặt hàng {0}.
        /// </summary>
        internal static string ImportProductCateDefaultOfProductNotFound {
            get {
                return ResourceManager.GetString("ImportProductCateDefaultOfProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy danh mục {0} cho mặt hàng {1}.
        /// </summary>
        internal static string ImportProductCateOfProductNotFound {
            get {
                return ResourceManager.GetString("ImportProductCateOfProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy loại mã {0} cho mặt hàng {1}.
        /// </summary>
        internal static string ImportProductTypeOfProductNotFound {
            get {
                return ResourceManager.GetString("ImportProductTypeOfProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng.
        /// </summary>
        internal static string ImportRowTitle {
            get {
                return ResourceManager.GetString("ImportRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục mặt hàng không tồn tại.
        /// </summary>
        internal static string ProductCateNotFound {
            get {
                return ResourceManager.GetString("ProductCateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã mặt hàng {0} đã tồn tại.
        /// </summary>
        internal static string ProductCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("ProductCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định mức vật tư tiêu hao.
        /// </summary>
        internal static string ProductConsumptionImportAsCateTitle {
            get {
                return ResourceManager.GetString("ProductConsumptionImportAsCateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt hàng.
        /// </summary>
        internal static string ProductImportAsCateTitle {
            get {
                return ResourceManager.GetString("ProductImportAsCateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng sử dụng của NVL có mã {0} trong nhóm {1} phải lơn hơn 0.
        /// </summary>
        internal static string ProductMaterialConsumptionQuantityError {
            get {
                return ResourceManager.GetString("ProductMaterialConsumptionQuantityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên mặt hàng có mã {0} không được để trống.
        /// </summary>
        internal static string ProductNameOfCodeEmpty {
            get {
                return ResourceManager.GetString("ProductNameOfCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không thể tính toán biểu thức đơn vị chuyển đổi {0}  của mặt hàng {1}.
        /// </summary>
        internal static string PuConversionExpressionError {
            get {
                return ResourceManager.GetString("PuConversionExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu thức chuyển đổi {0} của mặt hàng {1} không đúng.
        /// </summary>
        internal static string PuConversionExpressionInvalid {
            get {
                return ResourceManager.GetString("PuConversionExpressionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ chính xác {0} không đúng, độ chính xác phải trong khoảng {1} - {2}.
        /// </summary>
        internal static string PuDecimalPlaceNotValid {
            get {
                return ResourceManager.GetString("PuDecimalPlaceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy công đoạn {0} sử dụng mặt hàng {1}.
        /// </summary>
        internal static string StepOfMaterialNotFound {
            get {
                return ResourceManager.GetString("StepOfMaterialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho không tồn tại {0}.
        /// </summary>
        internal static string StockNameNotFound {
            get {
                return ResourceManager.GetString("StockNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn vị tính mặt hàng {0}.
        /// </summary>
        internal static string UnitOfProductNotFound {
            get {
                return ResourceManager.GetString("UnitOfProductNotFound", resourceCulture);
            }
        }
    }
}
