//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.ErrorCodes.Hr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HrErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HrErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.ErrorCodes.Hr.HrErrorCodeDescription", typeof(HrErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chức năng.
        /// </summary>
        public static string HrActionNotFound {
            get {
                return ResourceManager.GetString("HrActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vùng dữ liệu đã tồn tại.
        /// </summary>
        public static string HrAreaCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("HrAreaCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu của vùng đã tồn tại.
        /// </summary>
        public static string HrAreaFieldAlreadyExisted {
            get {
                return ResourceManager.GetString("HrAreaFieldAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không tồn tại.
        /// </summary>
        public static string HrAreaFieldNotFound {
            get {
                return ResourceManager.GetString("HrAreaFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy vùng dữ liệu.
        /// </summary>
        public static string HrAreaNotFound {
            get {
                return ResourceManager.GetString("HrAreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề vùng dữ liệu đã tồn tại.
        /// </summary>
        public static string HrAreaTitleAlreadyExisted {
            get {
                return ResourceManager.GetString("HrAreaTitleAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ hành chính nhân sự đã tồn tại.
        /// </summary>
        public static string HrCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("HrCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu đã tồn tại.
        /// </summary>
        public static string HrFieldAlreadyExisted {
            get {
                return ResourceManager.GetString("HrFieldAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSize của Trường dữ liệu kiểu Text không thể nhỏ hơn hoặc bằng 0.
        /// </summary>
        public static string HrFieldDataSizeInValid {
            get {
                return ResourceManager.GetString("HrFieldDataSizeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu đang được sử dụng.
        /// </summary>
        public static string HrFieldIsUsed {
            get {
                return ResourceManager.GetString("HrFieldIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không tồn tại.
        /// </summary>
        public static string HrFieldNotFound {
            get {
                return ResourceManager.GetString("HrFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chứng từ hành chính nhân sự đã tồn tại.
        /// </summary>
        public static string HrTitleAlreadyExisted {
            get {
                return ResourceManager.GetString("HrTitleAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chứng từ hành chính nhân sự.
        /// </summary>
        public static string HrTypeNotFound {
            get {
                return ResourceManager.GetString("HrTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ không tồn tại.
        /// </summary>
        public static string HrValueBillNotFound {
            get {
                return ResourceManager.GetString("HrValueBillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} dòng {1} trường dữ liệu {2} không hợp lệ.
        /// </summary>
        public static string HrValueInValid {
            get {
                return ResourceManager.GetString("HrValueInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình mã tự sinh thất bại.
        /// </summary>
        public static string MapGenCodeConfigFail {
            get {
                return ResourceManager.GetString("MapGenCodeConfigFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giá trị dòng {0} của trường {1} không tồn tại.
        /// </summary>
        public static string ReferValueNotFound {
            get {
                return ResourceManager.GetString("ReferValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giá trị dòng {0} của trường {1} không thỏa mãn điều kiện lọc.
        /// </summary>
        public static string ReferValueNotValidFilter {
            get {
                return ResourceManager.GetString("ReferValueNotValidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được phép để trống dòng {0} trường thông tin {1}.
        /// </summary>
        public static string RequiredFieldIsEmpty {
            get {
                return ResourceManager.GetString("RequiredFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường tham chiếu không tồn tại.
        /// </summary>
        public static string SourceCategoryFieldNotFound {
            get {
                return ResourceManager.GetString("SourceCategoryFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình chứng từ hành chính nhân sự nguồn không tồn tại.
        /// </summary>
        public static string SourceHrTypeNotFound {
            get {
                return ResourceManager.GetString("SourceHrTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường thông tin {0} có giá trị đã tồn tại.
        /// </summary>
        public static string UniqueValueAlreadyExisted {
            get {
                return ResourceManager.GetString("UniqueValueAlreadyExisted", resourceCulture);
            }
        }
    }
}
