USE [StockDB]
GO

INSERT INTO [dbo].[Inventory_Backup_DateUpdate]
           ([StockId]
           ,[InventoryCode]
           ,[InventoryTypeId]
           ,[Shipper]
           ,[Content]
           ,[Date]
           ,[CustomerId]
           ,[Department]
           ,[StockKeeperUserId]
           ,[BillCode]
           ,[CreatedByUserId]
           ,[UpdatedByUserId]
           ,[CreatedDatetimeUtc]
           ,[UpdatedDatetimeUtc]
           ,[IsDeleted]
           ,[IsApproved]
           ,[BillSerial]
           ,[BillDate]
           ,[TotalMoney]
           ,[InventoryId])
    SELECT
		[StockId]
           ,[InventoryCode]
           ,[InventoryTypeId]
           ,[Shipper]
           ,[Content]
           ,[Date]
           ,[CustomerId]
           ,[Department]
           ,[StockKeeperUserId]
           ,[BillCode]
           ,[CreatedByUserId]
           ,[UpdatedByUserId]
           ,[CreatedDatetimeUtc]
           ,[UpdatedDatetimeUtc]
           ,[IsDeleted]
           ,[IsApproved]
           ,[BillSerial]
           ,[BillDate]
           ,[TotalMoney]
           ,[InventoryId]
		   FROM Inventory
GO
UPDATE Inventory SET [Date] = DATEADD(hour,-7,Date) WHERE DATEPART(hour, Date)=0

