//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.PurchaseOrder.Voucher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VoucherConfigActivityLogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VoucherConfigActivityLogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.PurchaseOrder.Voucher.VoucherConfigActivityLogMessage", typeof(VoucherConfigActivityLogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chứng từ {0}.
        /// </summary>
        public static string CreateVoucher {
            get {
                return ResourceManager.GetString("CreateVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vùng thông tin {0}.
        /// </summary>
        public static string CreateVoucherArea {
            get {
                return ResourceManager.GetString("CreateVoucherArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string CreateVoucherFilter {
            get {
                return ResourceManager.GetString("CreateVoucherFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhóm chứng từ {0}.
        /// </summary>
        public static string CreateVoucherGroup {
            get {
                return ResourceManager.GetString("CreateVoucherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm trường dữ liệu chứng từ {0}.
        /// </summary>
        public static string CreateVoucherInfo {
            get {
                return ResourceManager.GetString("CreateVoucherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa loại chứng từ bán hàng {0}.
        /// </summary>
        public static string DeleteVoucher {
            get {
                return ResourceManager.GetString("DeleteVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá vùng thông tin {0}.
        /// </summary>
        public static string DeleteVoucherArea {
            get {
                return ResourceManager.GetString("DeleteVoucherArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa trường dữ liệu chung {0}.
        /// </summary>
        public static string DeleteVoucherField {
            get {
                return ResourceManager.GetString("DeleteVoucherField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bộ lọc {0} chứng từ  {1}.
        /// </summary>
        public static string DeleteVoucherFilter {
            get {
                return ResourceManager.GetString("DeleteVoucherFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhóm chứng từ {0}.
        /// </summary>
        public static string DeleteVoucherGroup {
            get {
                return ResourceManager.GetString("DeleteVoucherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vùng thông tin {0}.
        /// </summary>
        public static string UpdateVoucerArea {
            get {
                return ResourceManager.GetString("UpdateVoucerArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật loại chứng từ bán hàng {0}.
        /// </summary>
        public static string UpdateVoucher {
            get {
                return ResourceManager.GetString("UpdateVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cấu hình chung chứng từ bán hàng.
        /// </summary>
        public static string UpdateVoucherConfig {
            get {
                return ResourceManager.GetString("UpdateVoucherConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trường dữ liệu chung {0}.
        /// </summary>
        public static string UpdateVoucherField {
            get {
                return ResourceManager.GetString("UpdateVoucherField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string UpdateVoucherFilter {
            get {
                return ResourceManager.GetString("UpdateVoucherFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm chứng từ {0}.
        /// </summary>
        public static string UpdateVoucherGroup {
            get {
                return ResourceManager.GetString("UpdateVoucherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trường dữ liệu chứng từ {0}.
        /// </summary>
        public static string UpdateVoucherInfo {
            get {
                return ResourceManager.GetString("UpdateVoucherInfo", resourceCulture);
            }
        }
    }
}
