//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Stock.Inventory.InventoryFileData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InventoryDetailParseFacadeMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InventoryDetailParseFacadeMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Stock.Inventory.InventoryFileData.InventoryDetailParseFacadeMessag" +
                            "e", typeof(InventoryDetailParseFacadeMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy kiện để xuất, mặt hàng &quot;{0}&quot;.
        /// </summary>
        public static string NoPackageForInventoryOutput {
            get {
                return ResourceManager.GetString("NoPackageForInventoryOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy kiện &quot;{0}&quot;, mặt hàng &quot;{1}&quot;.
        /// </summary>
        public static string PackageCodeOfProductNotFound {
            get {
                return ResourceManager.GetString("PackageCodeOfProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thấy {0} mặt hàng &quot;{1}&quot;.
        /// </summary>
        public static string ProductFoundMoreThanOne {
            get {
                return ResourceManager.GetString("ProductFoundMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mặt hàng &quot;{0}&quot;.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đơn vị tính chính lỗi, mặt hàng &quot;{0}&quot;.
        /// </summary>
        public static string PuConversionDefaultError {
            get {
                return ResourceManager.GetString("PuConversionDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị chuyển đổi &quot;{0}&quot; khác với kiện &quot;{1}&quot; mặt hàng &quot;{2}&quot;.
        /// </summary>
        public static string PuConversionDiffToPackage {
            get {
                return ResourceManager.GetString("PuConversionDiffToPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thấy {0} đơn vị chuyển đổi &quot;{1}&quot; mặt hàng &quot;{2}&quot;.
        /// </summary>
        public static string PuConversionOfProductFoundMoreThanOne {
            get {
                return ResourceManager.GetString("PuConversionOfProductFoundMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn vị chuyển đổi &quot;{0}&quot; mặt hàng &quot;{1}&quot;.
        /// </summary>
        public static string PuConversionOfProductNotFound {
            get {
                return ResourceManager.GetString("PuConversionOfProductNotFound", resourceCulture);
            }
        }
    }
}
