//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.System.CategoryErrorCodeDescription", typeof(CategoryErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục đã tồn tại.
        /// </summary>
        public static string CategoryCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("CategoryCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trường đã tồn tại.
        /// </summary>
        public static string CategoryFieldNameAlreadyExisted {
            get {
                return ResourceManager.GetString("CategoryFieldNameAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không cần giá trị mặc định.
        /// </summary>
        public static string CategoryFieldNotDefaultValue {
            get {
                return ResourceManager.GetString("CategoryFieldNotDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không tồn tại.
        /// </summary>
        public static string CategoryFieldNotFound {
            get {
                return ResourceManager.GetString("CategoryFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không được phép thay đổi.
        /// </summary>
        public static string CategoryFieldReadOnly {
            get {
                return ResourceManager.GetString("CategoryFieldReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không phải là danh mục.
        /// </summary>
        public static string CategoryIsNotModule {
            get {
                return ResourceManager.GetString("CategoryIsNotModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục nằm ngoài phân hệ.
        /// </summary>
        public static string CategoryIsOutSideData {
            get {
                return ResourceManager.GetString("CategoryIsOutSideData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thông tin danh mục ngoài phân hệ thất bại.
        /// </summary>
        public static string CategoryIsOutSideDataError {
            get {
                return ResourceManager.GetString("CategoryIsOutSideDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy danh mục.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục không được phép thay đổi.
        /// </summary>
        public static string CategoryReadOnly {
            get {
                return ResourceManager.GetString("CategoryReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang có dòng dữ liệu sử dụng giá trị này.
        /// </summary>
        public static string CategoryRowAlreadyExisted {
            get {
                return ResourceManager.GetString("CategoryRowAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng thông tin không tồn tại.
        /// </summary>
        public static string CategoryRowNotFound {
            get {
                return ResourceManager.GetString("CategoryRowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục đã tồn tại.
        /// </summary>
        public static string CategoryTitleAlreadyExisted {
            get {
                return ResourceManager.GetString("CategoryTitleAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} không hợp lệ.
        /// </summary>
        public static string CategoryValueInValid {
            get {
                return ResourceManager.GetString("CategoryValueInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị không tồn tại.
        /// </summary>
        public static string CategoryValueNotFound {
            get {
                return ResourceManager.GetString("CategoryValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tồn tại tham chiếu tới danh mục này.
        /// </summary>
        public static string CatRelationshipAlreadyExisted {
            get {
                return ResourceManager.GetString("CatRelationshipAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu dữ liệu không tồn tại.
        /// </summary>
        public static string DataTypeNotFound {
            get {
                return ResourceManager.GetString("DataTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang có trường dữ liệu tham chiếu tới.
        /// </summary>
        public static string DestCategoryFieldAlreadyExisted {
            get {
                return ResourceManager.GetString("DestCategoryFieldAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không hợp lệ.
        /// </summary>
        public static string FormatFileInvalid {
            get {
                return ResourceManager.GetString("FormatFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu nhập liệu không tồn tại.
        /// </summary>
        public static string FormTypeNotFound {
            get {
                return ResourceManager.GetString("FormTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai kiểu nhập liệu không thể chuyển qua lại.
        /// </summary>
        public static string FormTypeNotSwitch {
            get {
                return ResourceManager.GetString("FormTypeNotSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không thuộc vào đơn vị.
        /// </summary>
        public static string InvalidSubsidiary {
            get {
                return ResourceManager.GetString("InvalidSubsidiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm dữ liệu đang trực thuộc danh mục.
        /// </summary>
        public static string IsSubCategory {
            get {
                return ResourceManager.GetString("IsSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tồn tại danh mục cha, loại bỏ liên kết trước khi xóa.
        /// </summary>
        public static string ParentCategoryAlreadyExisted {
            get {
                return ResourceManager.GetString("ParentCategoryAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu cha không được là chính nó.
        /// </summary>
        public static string ParentCategoryFromItSelf {
            get {
                return ResourceManager.GetString("ParentCategoryFromItSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu cha không tồn tại.
        /// </summary>
        public static string ParentCategoryRowNotExisted {
            get {
                return ResourceManager.GetString("ParentCategoryRowNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tham chiếu từ chính trường dữ liệu.
        /// </summary>
        public static string ReferenceFromItSelf {
            get {
                return ResourceManager.GetString("ReferenceFromItSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không tồn tại.
        /// </summary>
        public static string ReferValueNotFound {
            get {
                return ResourceManager.GetString("ReferValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tồn tại tham chiếu tới giá trị này.
        /// </summary>
        public static string RelationshipAlreadyExisted {
            get {
                return ResourceManager.GetString("RelationshipAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được phép để trống trường thông tin {0}.
        /// </summary>
        public static string RequiredFieldIsEmpty {
            get {
                return ResourceManager.GetString("RequiredFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường tham chiếu không tồn tại.
        /// </summary>
        public static string SourceCategoryFieldNotFound {
            get {
                return ResourceManager.GetString("SourceCategoryFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm dữ liệu đã tồn tại.
        /// </summary>
        public static string SubCategoryCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("SubCategoryCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm dữ liệu đã trực thuộc một danh mục khác.
        /// </summary>
        public static string SubCategoryHasParent {
            get {
                return ResourceManager.GetString("SubCategoryHasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm dữ liệu đang là danh mục.
        /// </summary>
        public static string SubCategoryIsModule {
            get {
                return ResourceManager.GetString("SubCategoryIsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhóm dữ liệu.
        /// </summary>
        public static string SubCategoryNotFound {
            get {
                return ResourceManager.GetString("SubCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm dữ liệu đã tồn tại.
        /// </summary>
        public static string SubCategoryTitleAlreadyExisted {
            get {
                return ResourceManager.GetString("SubCategoryTitleAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường thông tin {0} có giá trị đã tồn tại.
        /// </summary>
        public static string UniqueValueAlreadyExisted {
            get {
                return ResourceManager.GetString("UniqueValueAlreadyExisted", resourceCulture);
            }
        }
    }
}
