//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.System.CategoryErrorCodeDescription", typeof(CategoryErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục đã tồn tại.
        /// </summary>
        public static string CategoryCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("CategoryCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trường đã tồn tại.
        /// </summary>
        public static string CategoryFieldNameAlreadyExisted {
            get {
                return ResourceManager.GetString("CategoryFieldNameAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không tồn tại.
        /// </summary>
        public static string CategoryFieldNotFound {
            get {
                return ResourceManager.GetString("CategoryFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không được phép thay đổi.
        /// </summary>
        public static string CategoryFieldReadOnly {
            get {
                return ResourceManager.GetString("CategoryFieldReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục nằm ngoài phân hệ.
        /// </summary>
        public static string CategoryIsOutSideData {
            get {
                return ResourceManager.GetString("CategoryIsOutSideData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy danh mục.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục không được phép thay đổi.
        /// </summary>
        public static string CategoryReadOnly {
            get {
                return ResourceManager.GetString("CategoryReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng thông tin không tồn tại.
        /// </summary>
        public static string CategoryRowNotFound {
            get {
                return ResourceManager.GetString("CategoryRowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục đã tồn tại.
        /// </summary>
        public static string CategoryTitleAlreadyExisted {
            get {
                return ResourceManager.GetString("CategoryTitleAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị {0} không hợp lệ.
        /// </summary>
        public static string CategoryValueInValid {
            get {
                return ResourceManager.GetString("CategoryValueInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị không tồn tại.
        /// </summary>
        public static string CategoryValueNotFound {
            get {
                return ResourceManager.GetString("CategoryValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tồn tại tham chiếu tới danh mục này.
        /// </summary>
        public static string CatRelationshipAlreadyExisted {
            get {
                return ResourceManager.GetString("CatRelationshipAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSize của Trường dữ liệu kiểu Text không thể nhỏ hơn hoặc bằng 0.
        /// </summary>
        public static string DataSizeInValid {
            get {
                return ResourceManager.GetString("DataSizeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang có trường dữ liệu tham chiếu tới.
        /// </summary>
        public static string DestCategoryFieldAlreadyExisted {
            get {
                return ResourceManager.GetString("DestCategoryFieldAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tồn tại tham chiếu tới giá trị này.
        /// </summary>
        public static string HadSomeDataRelatedToThisValue {
            get {
                return ResourceManager.GetString("HadSomeDataRelatedToThisValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không thuộc vào đơn vị.
        /// </summary>
        public static string InvalidSubsidiary {
            get {
                return ResourceManager.GetString("InvalidSubsidiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu cha không được là chính nó.
        /// </summary>
        public static string ParentCategoryFromItSelf {
            get {
                return ResourceManager.GetString("ParentCategoryFromItSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu cha không tồn tại.
        /// </summary>
        public static string ParentCategoryRowNotExisted {
            get {
                return ResourceManager.GetString("ParentCategoryRowNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không tồn tại.
        /// </summary>
        public static string ReferValueNotFound {
            get {
                return ResourceManager.GetString("ReferValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được phép để trống trường thông tin {0}.
        /// </summary>
        public static string RequiredFieldIsEmpty {
            get {
                return ResourceManager.GetString("RequiredFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường tham chiếu không tồn tại.
        /// </summary>
        public static string SourceCategoryFieldNotFound {
            get {
                return ResourceManager.GetString("SourceCategoryFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường thông tin {0} có giá trị đã tồn tại.
        /// </summary>
        public static string UniqueValueAlreadyExisted {
            get {
                return ResourceManager.GetString("UniqueValueAlreadyExisted", resourceCulture);
            }
        }
    }
}
