//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.PurchaseOrder.PoProviderPricing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PoProviderPricingValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PoProviderPricingValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.PurchaseOrder.PoProviderPricing.PoProviderPricingValidationMessage" +
                            "", typeof(PoProviderPricingValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giá nhà cung cấp đã được duyệt.
        /// </summary>
        public static string AlreadyApproved {
            get {
                return ResourceManager.GetString("AlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giá nhà cung cấp đã được kiểm tra.
        /// </summary>
        public static string AlreadyChecked {
            get {
                return ResourceManager.GetString("AlreadyChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giá nhà cung cấp đã từ chối.
        /// </summary>
        public static string AlreadyRejected {
            get {
                return ResourceManager.GetString("AlreadyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ngày báo giá.
        /// </summary>
        public static string DateIsRequired {
            get {
                return ResourceManager.GetString("DateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ giao hàng quá dài.
        /// </summary>
        public static string DeleveryDestinationTooLong {
            get {
                return ResourceManager.GetString("DeleveryDestinationTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giá nhà cung cấp đã từ chối kiểm tra.
        /// </summary>
        public static string HasBeenFailAtCheck {
            get {
                return ResourceManager.GetString("HasBeenFailAtCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giá nhà cung cấp chưa được qua kiểm tra.
        /// </summary>
        public static string NotPassCheckYet {
            get {
                return ResourceManager.GetString("NotPassCheckYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo giá nhà cung cấp chưa được gửi để duyệt.
        /// </summary>
        public static string NotSentToCensorYet {
            get {
                return ResourceManager.GetString("NotSentToCensorYet", resourceCulture);
            }
        }
    }
}
