//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Organization.Department {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DepartmentActivityLogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DepartmentActivityLogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Organization.Department.DepartmentActivityLogMessage", typeof(DepartmentActivityLogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới bộ phận {0}.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bộ phận {0}.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm lịch làm việc {0} từ {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentCalendarCreate {
            get {
                return ResourceManager.GetString("DepartmentCalendarCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa lịch làm việc {0} từ {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentCalendarDelete {
            get {
                return ResourceManager.GetString("DepartmentCalendarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật lịch làm việc {0} từ {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentCalendarUpdate {
            get {
                return ResourceManager.GetString("DepartmentCalendarUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân sự tăng cường từ {0:dd/MM/yyyy} - {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentIncreaseCreate {
            get {
                return ResourceManager.GetString("DepartmentIncreaseCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân sự tăng cường từ {0:dd/MM/yyyy} - {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentIncreaseDelete {
            get {
                return ResourceManager.GetString("DepartmentIncreaseDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhân sự tăng cường từ {0:dd/MM/yyyy} - {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentIncreaseUpdate {
            get {
                return ResourceManager.GetString("DepartmentIncreaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tăng ca từ {0:dd/MM/yyyy} - {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentOverHourCreate {
            get {
                return ResourceManager.GetString("DepartmentOverHourCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tăng ca từ {0:dd/MM/yyyy} - {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentOverHourDelete {
            get {
                return ResourceManager.GetString("DepartmentOverHourDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tăng ca từ {0:dd/MM/yyyy} - {1:dd/MM/yyyy} cho bộ phận {2}.
        /// </summary>
        public static string DepartmentOverHourUpdate {
            get {
                return ResourceManager.GetString("DepartmentOverHourUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bộ phận {0}.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
