//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Accountancy.InputConfig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputConfigActivityLogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputConfigActivityLogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Accountancy.InputConfig.InputConfigActivityLogMessage", typeof(InputConfigActivityLogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vùng thông tin {0}.
        /// </summary>
        public static string CreateInputArea {
            get {
                return ResourceManager.GetString("CreateInputArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chứng từ {0}.
        /// </summary>
        public static string CreateInputData {
            get {
                return ResourceManager.GetString("CreateInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string CreateInputDataFilter {
            get {
                return ResourceManager.GetString("CreateInputDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhóm chứng từ {0}.
        /// </summary>
        public static string CreateInputDataGroup {
            get {
                return ResourceManager.GetString("CreateInputDataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm trường dữ liệu chứng từ {0}.
        /// </summary>
        public static string CreateInputField {
            get {
                return ResourceManager.GetString("CreateInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá vùng thông tin {0}.
        /// </summary>
        public static string DeleteInputArea {
            get {
                return ResourceManager.GetString("DeleteInputArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá chứng từ {0}.
        /// </summary>
        public static string DeleteInputData {
            get {
                return ResourceManager.GetString("DeleteInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string DeleteInputDataFilter {
            get {
                return ResourceManager.GetString("DeleteInputDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá nhóm chứng từ {0}.
        /// </summary>
        public static string DeleteInputDataGroup {
            get {
                return ResourceManager.GetString("DeleteInputDataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá trường dữ liệu chứng từ {0}.
        /// </summary>
        public static string DeleteInputField {
            get {
                return ResourceManager.GetString("DeleteInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cấu hình chung chứng từ kế toán.
        /// </summary>
        public static string UpdateGeneral {
            get {
                return ResourceManager.GetString("UpdateGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vùng thông tin {0}.
        /// </summary>
        public static string UpdateInputArea {
            get {
                return ResourceManager.GetString("UpdateInputArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chứng từ {0}.
        /// </summary>
        public static string UpdateInputData {
            get {
                return ResourceManager.GetString("UpdateInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string UpdateInputDataFilter {
            get {
                return ResourceManager.GetString("UpdateInputDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm chứng từ {0}.
        /// </summary>
        public static string UpdateInputDataGroup {
            get {
                return ResourceManager.GetString("UpdateInputDataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trường dữ liệu chứng từ {0}.
        /// </summary>
        public static string UpdateInputField {
            get {
                return ResourceManager.GetString("UpdateInputField", resourceCulture);
            }
        }
    }
}
