//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.ErrorCodes.PO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchasingSuggestErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchasingSuggestErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.ErrorCodes.PO.PurchasingSuggestErrorCodeDescription", typeof(PurchasingSuggestErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị mua hàng đang được phân công không được từ chối!.
        /// </summary>
        public static string CanNotRejectSuggestInUse {
            get {
                return ResourceManager.GetString("CanNotRejectSuggestInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phân công đã tồn tại.
        /// </summary>
        public static string PoAssignmentCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("PoAssignmentCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ được xác nhận phân công của mình!.
        /// </summary>
        public static string PoAssignmentConfirmInvalidCurrentUser {
            get {
                return ResourceManager.GetString("PoAssignmentConfirmInvalidCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xóa phân công mua hàng của mặt hàng với mặt hàng xóa!.
        /// </summary>
        public static string PoAssignmentDetailNotEmpty {
            get {
                return ResourceManager.GetString("PoAssignmentDetailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xóa phân công mua hàng của đơn đề nghị này trước khi xóa!.
        /// </summary>
        public static string PoAssignmentNotEmpty {
            get {
                return ResourceManager.GetString("PoAssignmentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phân công mua hàng.
        /// </summary>
        public static string PoAssignmentNotfound {
            get {
                return ResourceManager.GetString("PoAssignmentNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân công vượt mức đề nghị mua.
        /// </summary>
        public static string PoAssignmentOverload {
            get {
                return ResourceManager.GetString("PoAssignmentOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xóa PO liên quan đến mặt hàng phân công mua bị xóa!.
        /// </summary>
        public static string PurchaseOrderDetailNotEmpty {
            get {
                return ResourceManager.GetString("PurchaseOrderDetailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị mua hàng chưa được duyệt!.
        /// </summary>
        public static string PurchasingSuggestIsNotApprovedYet {
            get {
                return ResourceManager.GetString("PurchasingSuggestIsNotApprovedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thế xóa phiếu đề nghị mua hàng đã được duyệt.
        /// </summary>
        public static string SuggestAlreadyApproved {
            get {
                return ResourceManager.GetString("SuggestAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu đề nghị mua hàng đã tồn tại.
        /// </summary>
        public static string SuggestCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("SuggestCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phiếu đề nghị mua hàng không có.
        /// </summary>
        public static string SuggestCodeEmpty {
            get {
                return ResourceManager.GetString("SuggestCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm trong đề nghị mua hàng.
        /// </summary>
        public static string SuggestDetailNotfound {
            get {
                return ResourceManager.GetString("SuggestDetailNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phiếu đề nghị mua hàng tương ứng.
        /// </summary>
        public static string SuggestNotFound {
            get {
                return ResourceManager.GetString("SuggestNotFound", resourceCulture);
            }
        }
    }
}
