//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.ErrorCodes.Manufacturing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductionProcessErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductionProcessErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.ErrorCodes.Manufacturing.ProductionProcessErrorCodeDescripti" +
                            "on", typeof(ProductionProcessErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại quy trình sản xuất.
        /// </summary>
        public static string ExistsProductionProcess {
            get {
                return ResourceManager.GetString("ExistsProductionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa công đoạn.
        /// </summary>
        public static string InvalidDeleteProductionStep {
            get {
                return ResourceManager.GetString("InvalidDeleteProductionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các công đoạn không nằm trong cùng 1 quy trình sản xuất.
        /// </summary>
        public static string ListProductionStepNotInContainerId {
            get {
                return ResourceManager.GetString("ListProductionStepNotInContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy các chi tiết trong công đoạn.
        /// </summary>
        public static string NotFoundInOutStep {
            get {
                return ResourceManager.GetString("NotFoundInOutStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy quy trình sản xuất.
        /// </summary>
        public static string NotFoundProductionProcess {
            get {
                return ResourceManager.GetString("NotFoundProductionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy công đoạn.
        /// </summary>
        public static string NotFoundProductionStep {
            get {
                return ResourceManager.GetString("NotFoundProductionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy trình sản xuất không hợp lệ.
        /// </summary>
        public static string ValidateProductionStep {
            get {
                return ResourceManager.GetString("ValidateProductionStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất hiện chi tiết trùng nhau mã code.
        /// </summary>
        public static string ValidateProductionStepLinkData {
            get {
                return ResourceManager.GetString("ValidateProductionStepLinkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi vai trò vào ra của mặt hàng trong quy trình sản xuất.
        /// </summary>
        public static string ValidateProductionStepLinkDataRole {
            get {
                return ResourceManager.GetString("ValidateProductionStepLinkDataRole", resourceCulture);
            }
        }
    }
}
