//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VErp.Commons.Enums.Resources.ErrorCodes.Manufacturing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutsourceErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutsourceErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VErp.Commons.Enums.Resources.ErrorCodes.Manufacturing.OutsourceErrorCodeDescripti" +
                            "on", typeof(OutsourceErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo đơn hàng gia công.
        /// </summary>
        internal static string CanNotCreateOutsourceOrder {
            get {
                return ResourceManager.GetString("CanNotCreateOutsourceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại công đoạn có yêu cầu gia công.
        /// </summary>
        internal static string EarlyExistsProductionStepHadOutsourceRequest {
            get {
                return ResourceManager.GetString("EarlyExistsProductionStepHadOutsourceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu gia công không hợp lệ.
        /// </summary>
        internal static string InValidRequestOutsource {
            get {
                return ResourceManager.GetString("InValidRequestOutsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn hàng gia công.
        /// </summary>
        internal static string NotFoundOutsourceOrder {
            get {
                return ResourceManager.GetString("NotFoundOutsourceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy yêu cầu gia công chi tiết.
        /// </summary>
        internal static string NotFoundOutsourOrderDetail {
            get {
                return ResourceManager.GetString("NotFoundOutsourOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy yêu cầu gia công.
        /// </summary>
        internal static string NotFoundRequest {
            get {
                return ResourceManager.GetString("NotFoundRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại mã code trong hệ thống.
        /// </summary>
        internal static string OutsoureOrderCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("OutsoureOrderCodeAlreadyExisted", resourceCulture);
            }
        }
    }
}
