//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.Stock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackageErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.Stock.PackageErrorCodeDescription", typeof(PackageErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiện mặc định không được phép gộp.
        /// </summary>
        public static string CanNotJoinDefaultPackage {
            get {
                return ResourceManager.GetString("CanNotJoinDefaultPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiện hàng đang tồn tại một lượng chờ duyệt.
        /// </summary>
        public static string HasSomeQualtityWaitingForApproved {
            get {
                return ResourceManager.GetString("HasSomeQualtityWaitingForApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiện đã tồn tại.
        /// </summary>
        public static string PackageAlreadyExisted {
            get {
                return ResourceManager.GetString("PackageAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kiện không có.
        /// </summary>
        public static string PackageCodeEmpty {
            get {
                return ResourceManager.GetString("PackageCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiện này không cho phép cập nhật.
        /// </summary>
        public static string PackageNotAllowUpdate {
            get {
                return ResourceManager.GetString("PackageNotAllowUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy kiện tương ứng.
        /// </summary>
        public static string PackageNotFound {
            get {
                return ResourceManager.GetString("PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các kiện được gộp phải cùng kho chứa, mặt hàng và đơn vị tính (cùng đơn vị chuyển đổi).
        /// </summary>
        public static string PackagesToJoinMustBeSameProductAndUnit {
            get {
                return ResourceManager.GetString("PackagesToJoinMustBeSameProductAndUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hàng trong kiện không đủ.
        /// </summary>
        public static string QualtityOfProductInPackageNotEnough {
            get {
                return ResourceManager.GetString("QualtityOfProductInPackageNotEnough", resourceCulture);
            }
        }
    }
}
