//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.ErrorCodes.Organization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DepartmentErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DepartmentErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.ErrorCodes.Organization.DepartmentErrorCodeDescription", typeof(DepartmentErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận đang hoạt động, chỉ được phép xóa bộ phận không hoạt động.
        /// </summary>
        public static string DepartmentActived {
            get {
                return ResourceManager.GetString("DepartmentActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại bộ phận trực thuộc đang hoạt động.
        /// </summary>
        public static string DepartmentChildActivedAlreadyExisted {
            get {
                return ResourceManager.GetString("DepartmentChildActivedAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại bộ phận trực thuộc.
        /// </summary>
        public static string DepartmentChildAlreadyExisted {
            get {
                return ResourceManager.GetString("DepartmentChildAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối bộ phận đã tồn tại.
        /// </summary>
        public static string DepartmentCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("DepartmentCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận đang không hoạt động.
        /// </summary>
        public static string DepartmentInActived {
            get {
                return ResourceManager.GetString("DepartmentInActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận đang được sử dụng {0}.
        /// </summary>
        public static string DepartmentInUsed {
            get {
                return ResourceManager.GetString("DepartmentInUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bộ phận đã tồn tại.
        /// </summary>
        public static string DepartmentNameAlreadyExisted {
            get {
                return ResourceManager.GetString("DepartmentNameAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bộ phận.
        /// </summary>
        public static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận chủ quản đang không hoạt động.
        /// </summary>
        public static string DepartmentParentInActived {
            get {
                return ResourceManager.GetString("DepartmentParentInActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bộ phận chủ quản.
        /// </summary>
        public static string DepartmentParentNotFound {
            get {
                return ResourceManager.GetString("DepartmentParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại nhân sự trực thuộc đang hoạt động.
        /// </summary>
        public static string DepartmentUserActivedAlreadyExisted {
            get {
                return ResourceManager.GetString("DepartmentUserActivedAlreadyExisted", resourceCulture);
            }
        }
    }
}
