//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.ErrorCodes.Voucher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VoucherErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VoucherErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.ErrorCodes.Voucher.VoucherErrorCodeDescription", typeof(VoucherErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu dữ liệu không tồn tại.
        /// </summary>
        public static string DataTypeNotFound {
            get {
                return ResourceManager.GetString("DataTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không hợp lệ.
        /// </summary>
        public static string FormatFileInvalid {
            get {
                return ResourceManager.GetString("FormatFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu nhập liệu không tồn tại.
        /// </summary>
        public static string FormTypeNotFound {
            get {
                return ResourceManager.GetString("FormTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vùng dữ liệu đang trực thuộc chứng từ.
        /// </summary>
        public static string IsVoucherArea {
            get {
                return ResourceManager.GetString("IsVoucherArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình mã tự sinh thất bại.
        /// </summary>
        public static string MapGenCodeConfigFail {
            get {
                return ResourceManager.GetString("MapGenCodeConfigFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vùng dữ liệu dạng bảng đã tồn tại.
        /// </summary>
        public static string MultiRowAreaAlreadyExisted {
            get {
                return ResourceManager.GetString("MultiRowAreaAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin dữ liệu dạng bảng không được để trống.
        /// </summary>
        public static string MultiRowAreaEmpty {
            get {
                return ResourceManager.GetString("MultiRowAreaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cấu hình phiếu in đã tồn tại.
        /// </summary>
        public static string PrintConfigNameAlreadyExisted {
            get {
                return ResourceManager.GetString("PrintConfigNameAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy cấu hình phiếu in.
        /// </summary>
        public static string PrintConfigNotFound {
            get {
                return ResourceManager.GetString("PrintConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giá trị dòng {0} của trường {1} không tồn tại.
        /// </summary>
        public static string ReferValueNotFound {
            get {
                return ResourceManager.GetString("ReferValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giá trị dòng {0} của trường {1} không thỏa mãn điều kiện lọc.
        /// </summary>
        public static string ReferValueNotValidFilter {
            get {
                return ResourceManager.GetString("ReferValueNotValidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được phép để trống dòng {0} trường thông tin {1}.
        /// </summary>
        public static string RequiredFieldIsEmpty {
            get {
                return ResourceManager.GetString("RequiredFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường tham chiếu không tồn tại.
        /// </summary>
        public static string SourceCategoryFieldNotFound {
            get {
                return ResourceManager.GetString("SourceCategoryFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình chứng từ nguồn không tồn tại.
        /// </summary>
        public static string SourceVoucherTypeNotFound {
            get {
                return ResourceManager.GetString("SourceVoucherTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường thông tin {0} có giá trị &quot;{1}&quot; đã tồn tại .
        /// </summary>
        public static string UniqueValueAlreadyExisted {
            get {
                return ResourceManager.GetString("UniqueValueAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chức năng đã tồn tại.
        /// </summary>
        public static string VoucherActionCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherActionCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chức năng.
        /// </summary>
        public static string VoucherActionNotFound {
            get {
                return ResourceManager.GetString("VoucherActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vùng dữ liệu đã tồn tại.
        /// </summary>
        public static string VoucherAreaCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherAreaCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu đã tồn tại.
        /// </summary>
        public static string VoucherAreaFieldAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherAreaFieldAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không tồn tại.
        /// </summary>
        public static string VoucherAreaFieldNotFound {
            get {
                return ResourceManager.GetString("VoucherAreaFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không còn trường dữ liệu trống.
        /// </summary>
        public static string VoucherAreaFieldOverLoad {
            get {
                return ResourceManager.GetString("VoucherAreaFieldOverLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy vùng dữ liệu.
        /// </summary>
        public static string VoucherAreaNotFound {
            get {
                return ResourceManager.GetString("VoucherAreaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề vùng dữ liệu đã tồn tại.
        /// </summary>
        public static string VoucherAreaTitleAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherAreaTitleAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ đã tồn tại.
        /// </summary>
        public static string VoucherCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu dùng chung đã tồn tại.
        /// </summary>
        public static string VoucherFieldAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherFieldAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu dùng chung đang được sử dụng.
        /// </summary>
        public static string VoucherFieldIsUsed {
            get {
                return ResourceManager.GetString("VoucherFieldIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu dùng chung không tồn tại.
        /// </summary>
        public static string VoucherFieldNotFound {
            get {
                return ResourceManager.GetString("VoucherFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không phải là chứng từ.
        /// </summary>
        public static string VoucherIsNotModule {
            get {
                return ResourceManager.GetString("VoucherIsNotModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ không được phép thay đổi.
        /// </summary>
        public static string VoucherReadOnly {
            get {
                return ResourceManager.GetString("VoucherReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang có dòng dữ liệu sử dụng giá trị này.
        /// </summary>
        public static string VoucherRowAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherRowAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng thông tin không tồn tại.
        /// </summary>
        public static string VoucherRowNotFound {
            get {
                return ResourceManager.GetString("VoucherRowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chứng từ đã tồn tại.
        /// </summary>
        public static string VoucherTitleAlreadyExisted {
            get {
                return ResourceManager.GetString("VoucherTitleAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chứng từ.
        /// </summary>
        public static string VoucherTypeNotFound {
            get {
                return ResourceManager.GetString("VoucherTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng từ không tồn tại.
        /// </summary>
        public static string VoucherValueBillNotFound {
            get {
                return ResourceManager.GetString("VoucherValueBillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị dòng {0} trường dữ liệu {1} không hợp lệ.
        /// </summary>
        public static string VoucherValueInValid {
            get {
                return ResourceManager.GetString("VoucherValueInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị không tồn tại.
        /// </summary>
        public static string VoucherValueNotFound {
            get {
                return ResourceManager.GetString("VoucherValueNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataSize của Trường dữ liệu kiểu Text không thể nhỏ hơn hoặc bằng 0.
        /// </summary>
        public static string VoucherFieldDataSizeInValid {
            get
            {
                return ResourceManager.GetString("VoucherFieldDataSizeInValid", resourceCulture);
            }
        }
    }
}
