//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Enums.ErrorCodes.Product {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductErrorCodeDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductErrorCodeDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Enums.ErrorCodes.Product.ProductErrorCodeDescription", typeof(ProductErrorCodeDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không thể tính toán biểu thức đơn vị chuyển đổi.
        /// </summary>
        public static string InvalidUnitConversionExpression {
            get {
                return ResourceManager.GetString("InvalidUnitConversionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục mặt hàng không đúng.
        /// </summary>
        public static string ProductCateInvalid {
            get {
                return ResourceManager.GetString("ProductCateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã mặt hàng đã tồn tại.
        /// </summary>
        public static string ProductCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("ProductCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã mặt hàng không được để trống.
        /// </summary>
        public static string ProductCodeEmpty {
            get {
                return ResourceManager.GetString("ProductCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt hàng đang được sử dụng.
        /// </summary>
        public static string ProductInUsed {
            get {
                return ResourceManager.GetString("ProductInUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên mặt hàng đã tồn tại.
        /// </summary>
        public static string ProductNameAlreadyExisted {
            get {
                return ResourceManager.GetString("ProductNameAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên mặt hàng không được để rỗng.
        /// </summary>
        public static string ProductNameEmpty {
            get {
                return ResourceManager.GetString("ProductNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mặt hàng.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sinh mã mặt hàng không đúng.
        /// </summary>
        public static string ProductTypeInvalid {
            get {
                return ResourceManager.GetString("ProductTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng sử dụng của NVL tiêu hao bằng 0.
        /// </summary>
        public static string QuantityOfMaterialsConsumptionIsZero {
            get {
                return ResourceManager.GetString("QuantityOfMaterialsConsumptionIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị chuyển đổi đang được sử dụng.
        /// </summary>
        public static string SomeProductUnitConversionInUsed {
            get {
                return ResourceManager.GetString("SomeProductUnitConversionInUsed", resourceCulture);
            }
        }
    }
}
