//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Organization.Salary.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SalaryPeriodAdditionTypeValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalaryPeriodAdditionTypeValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Organization.Salary.Validation.SalaryPeriodAdditionTypeValidationM" +
                            "essage", typeof(SalaryPeriodAdditionTypeValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ {0} đã tồn tại, vui lòng chọn mã khác.
        /// </summary>
        public static string BillCodeAlreadyExisted {
            get {
                return ResourceManager.GetString("BillCodeAlreadyExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập mã chứng từ.
        /// </summary>
        public static string BillCodeIsRequired {
            get {
                return ResourceManager.GetString("BillCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên tại dòng {0} không tồn tại.
        /// </summary>
        public static string EmployeeDoseNotExisted {
            get {
                return ResourceManager.GetString("EmployeeDoseNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên {0} trùng lặp nhiều lần, dòng {1}.
        /// </summary>
        public static string EmployeeExistingMultitime {
            get {
                return ResourceManager.GetString("EmployeeExistingMultitime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể loại bỏ trường {0} {1} ra khỏi loại Thưởng/Phụ cấp và khấu trừ {2} do đã phát sinh dữ liệu.
        /// </summary>
        public static string FieldInTypeInUsed {
            get {
                return ResourceManager.GetString("FieldInTypeInUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu có ít nhất một dòng chi tiết chứng từ {0}.
        /// </summary>
        public static string RequireAtLeastOneDetail {
            get {
                return ResourceManager.GetString("RequireAtLeastOneDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chứng từ Thưởng/Phụ cấp và khấu trừ {0} đã ngưng hoạt động.
        /// </summary>
        public static string TypeInActived {
            get {
                return ResourceManager.GetString("TypeInActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chứng từ Thưởng/Phụ cấp và khấu trừ {0} đang được sử dụng.
        /// </summary>
        public static string TypeInUsed {
            get {
                return ResourceManager.GetString("TypeInUsed", resourceCulture);
            }
        }
    }
}
