//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.PurchaseOrder.Calc.PropertyCalc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyCalcValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyCalcValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.PurchaseOrder.Calc.PropertyCalc.PropertyCalcValidationMessage", typeof(PropertyCalcValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương án cắt có vật tư dư thừa bị trùng lặp.
        /// </summary>
        public static string DuplicatedExcessMaterialCuttingNameMustBeNotEmpty {
            get {
                return ResourceManager.GetString("DuplicatedExcessMaterialCuttingNameMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương án cắt có chi tiết đầu ra bị trùng lặp.
        /// </summary>
        public static string DuplicatedOutputCutting {
            get {
                return ResourceManager.GetString("DuplicatedOutputCutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vật tư dư thừa không được để trống.
        /// </summary>
        public static string ExcessMaterialCuttingNameMustBeNotEmpty {
            get {
                return ResourceManager.GetString("ExcessMaterialCuttingNameMustBeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số không được để trống.
        /// </summary>
        public static string PropertyCalcCodeEmpty {
            get {
                return ResourceManager.GetString("PropertyCalcCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bảng tính.
        /// </summary>
        public static string PropertyCalcNotFound {
            get {
                return ResourceManager.GetString("PropertyCalcNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số đã tồn tại.
        /// </summary>
        public static string PropertyCodeAlreadyExist {
            get {
                return ResourceManager.GetString("PropertyCodeAlreadyExist", resourceCulture);
            }
        }
    }
}
