//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Organization.HrType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HrTypeActivityLogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HrTypeActivityLogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Organization.HrType.HrTypeActivityLogMessage", typeof(HrTypeActivityLogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chứng từ hành chính nhân sự {0}.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vùng thông tin {0} của chứng từ hành chính nhân sự {1}.
        /// </summary>
        public static string CreateHrArea {
            get {
                return ResourceManager.GetString("CreateHrArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm trường dữ liệu {0} cho vùng thông tin {1}.
        /// </summary>
        public static string CreateHrFieldArea {
            get {
                return ResourceManager.GetString("CreateHrFieldArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string CreateHrFilter {
            get {
                return ResourceManager.GetString("CreateHrFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhóm chứng từ hành chính nhân sự {0}.
        /// </summary>
        public static string CreateHrGroup {
            get {
                return ResourceManager.GetString("CreateHrGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chứng từ {0}.
        /// </summary>
        public static string CreateHrType {
            get {
                return ResourceManager.GetString("CreateHrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá chứng từ hành chính nhân sự {0}.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá vùng thông tin {0} của chứng từ hành chính nhân sự {1}.
        /// </summary>
        public static string DeleteHrArea {
            get {
                return ResourceManager.GetString("DeleteHrArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá trường dữ liệu chứng từ {0}.
        /// </summary>
        public static string DeleteHrField {
            get {
                return ResourceManager.GetString("DeleteHrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá trường dữ liệu {0} cho vùng thông tin {1}.
        /// </summary>
        public static string DeleteHrFieldArea {
            get {
                return ResourceManager.GetString("DeleteHrFieldArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string DeleteHrFilter {
            get {
                return ResourceManager.GetString("DeleteHrFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá nhóm chứng từ hành chính nhân sự {0}.
        /// </summary>
        public static string DeleteHrGroup {
            get {
                return ResourceManager.GetString("DeleteHrGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá chứng từ {0}.
        /// </summary>
        public static string DeleteHrType {
            get {
                return ResourceManager.GetString("DeleteHrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chứng từ hành chính nhân sự {0}.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vùng thông tin {0} của chứng từ hành chính nhân sự {1}.
        /// </summary>
        public static string UpdateHrArea {
            get {
                return ResourceManager.GetString("UpdateHrArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cấu hình chung chứng từ hành chính nhân sự.
        /// </summary>
        public static string UpdateHrConfig {
            get {
                return ResourceManager.GetString("UpdateHrConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trường dữ liệu chứng từ {0}.
        /// </summary>
        public static string UpdateHrField {
            get {
                return ResourceManager.GetString("UpdateHrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trường dữ liệu {0} cho vùng thông tin {1}.
        /// </summary>
        public static string UpdateHrFieldArea {
            get {
                return ResourceManager.GetString("UpdateHrFieldArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bộ lọc {0} cho chứng từ  {1}.
        /// </summary>
        public static string UpdateHrFilter {
            get {
                return ResourceManager.GetString("UpdateHrFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm chứng từ hành chính nhân sự {0}.
        /// </summary>
        public static string UpdateHrGroup {
            get {
                return ResourceManager.GetString("UpdateHrGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chứng từ {0}.
        /// </summary>
        public static string UpdateHrType {
            get {
                return ResourceManager.GetString("UpdateHrType", resourceCulture);
            }
        }
    }
}
