//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VErp.Services.PurchaseOrder.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PurchasingRequestMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchasingRequestMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VErp.Services.PurchaseOrder.Service.Resources.PurchasingRequestMessage", typeof(PurchasingRequestMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete purchasing request because there are some linked purchasing suggests {0}.
        /// </summary>
        internal static string CanNotDeletePurchasingRequestWithExistedSuggest {
            get {
                return ResourceManager.GetString("CanNotDeletePurchasingRequestWithExistedSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while calculate quantity item {0}.
        /// </summary>
        internal static string ErrorCalcQuantity {
            get {
                return ResourceManager.GetString("ErrorCalcQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} items  {1} found.
        /// </summary>
        internal static string FoundNumberProduct {
            get {
                return ResourceManager.GetString("FoundNumberProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were {0} product units {1} of item {2} found.
        /// </summary>
        internal static string FoundNumberPuOfProduct {
            get {
                return ResourceManager.GetString("FoundNumberPuOfProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quantity of item {0}.
        /// </summary>
        internal static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items  {0} found.
        /// </summary>
        internal static string NoProductFound {
            get {
                return ResourceManager.GetString("NoProductFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product units {0} of item {1} was not found.
        /// </summary>
        internal static string NoPuOfProductFound {
            get {
                return ResourceManager.GetString("NoPuOfProductFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product unit conversion does not belong to.
        /// </summary>
        internal static string PuConversionDoesNotBelongToProduct {
            get {
                return ResourceManager.GetString("PuConversionDoesNotBelongToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default unit of item {0} was not found.
        /// </summary>
        internal static string PuDefaultError {
            get {
                return ResourceManager.GetString("PuDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not edit purchasing request from {0}.
        /// </summary>
        internal static string PurchasingRequestPreventFrom {
            get {
                return ResourceManager.GetString("PurchasingRequestPreventFrom", resourceCulture);
            }
        }
    }
}
