//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verp.Resources.Report.DashboardConfig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardConfigActivityLogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardConfigActivityLogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Verp.Resources.Report.DashboardConfig.DashboardConfigActivityLogMessage", typeof(DashboardConfigActivityLogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm biểu đồ báo cáo {0}.
        /// </summary>
        public static string CreateDashBoard {
            get {
                return ResourceManager.GetString("CreateDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bộ lọc {0} cho biểu đồ báo cáo  {1}.
        /// </summary>
        public static string CreateDashBoardFilter {
            get {
                return ResourceManager.GetString("CreateDashBoardFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhóm biểu đồ báo cáo {0}.
        /// </summary>
        public static string CreateDashBoardGroup {
            get {
                return ResourceManager.GetString("CreateDashBoardGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá biểu đồ báo cáo {0}.
        /// </summary>
        public static string DeleteDashBoard {
            get {
                return ResourceManager.GetString("DeleteDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá bộ lọc {0} cho biểu đồ báo cáo  {1}.
        /// </summary>
        public static string DeleteDashBoardFilter {
            get {
                return ResourceManager.GetString("DeleteDashBoardFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá nhóm biểu đồ báo cáo {0}.
        /// </summary>
        public static string DeleteDashBoardGroup {
            get {
                return ResourceManager.GetString("DeleteDashBoardGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật biểu đồ báo cáo {0}.
        /// </summary>
        public static string UpdateDashBoard {
            get {
                return ResourceManager.GetString("UpdateDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bộ lọc {0} cho biểu đồ báo cáo  {1}.
        /// </summary>
        public static string UpdateDashBoardFilter {
            get {
                return ResourceManager.GetString("UpdateDashBoardFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm biểu đồ báo cáo {0}.
        /// </summary>
        public static string UpdateDashBoardGroup {
            get {
                return ResourceManager.GetString("UpdateDashBoardGroup", resourceCulture);
            }
        }
    }
}
